src/Entity/Intervenant.php
<?php

namespace App\Entity;

use App\Repository\IntervenantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: IntervenantRepository::class)]
class Intervenant
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\OneToMany(targetEntity: Review::class, mappedBy: 'intervenant')]
    #[ORM\OrderBy(['createdAt' => 'DESC'])]
    private Collection $reviews;

    #[ORM\ManyToMany(targetEntity: Classe::class, inversedBy: 'intervenants')]
    #[ORM\JoinTable(name: 'intervenant_classe')]
    private Collection $classesTaught;

    #[ORM\ManyToMany(targetEntity: Matiere::class, inversedBy: 'intervenants')]
    #[ORM\JoinTable(name: 'intervenant_matiere')]
    private Collection $matieresEnseignees;
    //Default profile picture is a question mark
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $profilePictureFileName = "default-intervenant.png";

    public function __construct()
    {
        $this->reviews = new ArrayCollection();
        $this->classesTaught = new ArrayCollection();
        $this->matieresEnseignees = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }
    public function getImagePath() {
        $imagepath = "uploads/profilePictures/".$this->profilePictureFileName;
        return $imagepath;
    }
    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, Classe>
     */




    /**
     * @return Collection<int, Review>
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): static
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews->add($review);
            $review->setIntervenant($this);
        }

        return $this;
    }

    public function removeReview(Review $review): static
    {
        if ($this->reviews->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getIntervenant() === $this) {
                $review->setIntervenant(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Classe>
     */
    public function getClassesTaught(): Collection
    {
        return $this->classesTaught;
    }

    public function addClassesTaught(Classe $classesTaught): static
    {
        if (!$this->classesTaught->contains($classesTaught)) {
            $this->classesTaught->add($classesTaught);
            if (!$classesTaught->getIntervenants()->contains($this)) {
                $classesTaught->addIntervenant($this);
            }
        }

        return $this;
    }

    public function removeClassesTaught(Classe $classesTaught): static
    {
        if ($this->classesTaught->removeElement($classesTaught)) {

            if ($classesTaught->getIntervenants()->contains($this)) {
                $classesTaught->removeIntervenant($this);
            }

    }        return $this;

    }

    /**
     * @return Collection<int, Matiere>
     */
    public function getMatieresEnseignees(): Collection
    {
        return $this->matieresEnseignees;
    }

    public function addMatieresEnseignee(Matiere $matieresEnseignee): static
    {
        if (!$this->matieresEnseignees->contains($matieresEnseignee)) {
            $this->matieresEnseignees->add($matieresEnseignee);
            $matieresEnseignee->addIntervenant($this);
        }

        return $this;
    }

    public function removeMatieresEnseignee(Matiere $matieresEnseignee): static
    {
        if ($this->matieresEnseignees->removeElement($matieresEnseignee)) {
            $matieresEnseignee->removeIntervenant($this);
        }

        return $this;
    }

    public function getProfilePictureFileName(): ?string
    {
        return $this->profilePictureFileName;
    }

    public function setProfilePictureFileName(?string $profilePictureFileName): static
    {
        $this->profilePictureFileName = $profilePictureFileName;

        return $this;
    }
    public function getAverage() {
        $sum = 0;
        $count = 0;
        foreach ($this->reviews as $review) {
            $sum += $review->getGrade();
            $count++;
        }
        if ($count == 0) {
            return "Pas encore noté";
        }
        return  "Note moyenne : ".(string)round($sum / $count, 2)."/5";
    }
    public function getAverageParMatiere(Matiere $matiere) {
        $reviewsMatiere = $this->getReviews()->filter(fn(Review $review) => $review->getMatiere() === $matiere);
        $sum = 0;
        $count = 0;
        foreach ($reviewsMatiere as $review) {
            $sum += $review->getGrade();
            $count++;
        }
        if ($count == 0) {
            return "Pas encore noté";
        }
        $s = "(".(string)round($sum / $count, 2)."/5".")";
        return $s ;
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\BlogPost;
use App\Entity\Intervenant;
use App\Form\BlogPostType;
use App\Repository\BlogPostRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/blog')]
class BlogController extends AbstractController
{   
    public function __construct(private readonly Security $security, private readonly EntityManagerInterface $entityManager)
    {
    }
    #[Route('', name: 'app_blog_index', methods: ['GET'])]
    #[IsGranted("ROLE_USER")]
    public function index( Request $request): Response
    {

        $user = $this->getUser();
        //show every intervenant for admins
        if ($this->security->isGranted('ROLE_ADMIN')) {
            $professeurs = $this->entityManager->getRepository(Intervenant::class)->findAll();
        } else {
            //Previously, you would see intervenants added for your class with no matieres, now you see intervenants that teach your matieres
            $professeurs = $this->entityManager->getRepository(Intervenant::class)->findAllWithMatieresFromUser($user);
        }
        return $this->render('blog/index.html.twig', [
            'professeurs' => $professeurs,
        ]);
    }

  

}

templates/blog/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Tes intervenants{% endblock %}

{% block stylesheets %}
  {{ parent() }}
  <link rel="stylesheet" href="{{ asset('css/blog.css') }}">
{% endblock %}

{% block body %}
<h1 class="text-center my-5">Liste des professeurs de ta classe</h1>
  <!-- Breadcrumb -->
  <div class="container-center">
    <nav aria-label="breadcrumb" class="main-breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a title="accueil" href={{path('app_home')}}>Accueil</a></li>
        <li class="breadcrumb-item active" aria-current="page">Intervenants</li>
      </ol>
    </nav>
  </div>
  <!-- /Breadcrumb -->
  <div class="row">
    {% for professeur in professeurs %}
      <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="card">
          <img src="{{ asset("uploads/images/" ~ professeur.profilePictureFileName) }}" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">{{ professeur.name }}</h5>
            <span>{{ professeur.average }}</span>

            {% if professeur.matieresEnseignees is not empty %}
              <p class="card-text text-muted">Matière(s) enseignée(s):</p>
              <ul>
                {% for matiere in professeur.matieresEnseignees %}
                  <li>{{ matiere.name }}
                    {{ professeur.getAverageParMatiere(matiere) }}
                  </li> {% endfor %}
              </ul>
            {% else %}
              <p class="card-text text-muted" style="font-size: 0.8rem;">Aucune matière enseignée.</p>
            {% endif %}
            <a title="voir intervenant" href="{{ path('app_intervenant_show', { 'id' : professeur.id}) }}" class="btn btn-primary">Voir</a>

          </div>
        </div>
      </div>
    {% endfor %}
  </div>

{% endblock %}